#pragma once

#include <vector>
#include <string>

enum SCRIPT_TYPE
{
	ANIFINISHDESTROYSCRIPT,
	BUGNPCSCRIPT,
	BUGROLLINGSCRIPT,
	CACTUSNEEDLESCRIPT,
	CAMERAMOVESCRIPT,
	CAMERAPLAYERTRACKINGSCRIPT,
	COUNTDOWNDELETESCRIPT,
	FLOWERLIGHTAREASCRIPT,
	FLOWERLIGHTSCRIPT,
	GLOWINGPLANTSSCRIPT,
	GRASSSCRIPT,
	HPSCRIPT,
	INTERACTIONSCRIPT,
	JELLYBOMBDETECTSCRIPT,
	JELLYBOMBSCRIPT,
	JELLYPUSHFRAMESCRIPT,
	JELLYPUSHSCRIPT,
	LIFTSCRIPT,
	MISSILESCRIPT,
	MONSTERSCRIPT,
	NPCSCRIPT,
	OGUDANCEPOINTLIGHTSCRIPT,
	PLAYERCAMERASCRIPT,
	PLAYERDETECTSCRIPT,
	PLAYERINTERACTIONSCRIPT,
	PLAYERSCRIPT,
	PUSHSCRIPT,
	SPITCACTUSSCRIPT,
	STONEBREAKABLESCRIPT,
	SWINGOBJSCRIPT,
	TEXTBOXSCRIPT,
	UISCRIPT,
};

using namespace std;

class CScript;

class CScriptMgr
{
public:
	static void GetScriptInfo(vector<wstring>& _vec);
	static CScript * GetScript(const wstring& _strScriptName);
	static CScript * GetScript(UINT _iScriptType);
	static const wchar_t * GetScriptName(CScript * _pScript);
};
